### ISSUE TITLE
In pins_arduino.h correspondence between bit mask and pin PD5 is missing, while PD4 is repeated as D24, so D24 should be PD5

### ISSUE THREAD

**Issue by dmjlambert** [sparkfun/SF32u4_boards#15]
In Leonardo hardware pin assignment, the correspondence between bit mask and pin PD5 is missing, while PD4 is repeated as D24, so D24 should be PD5.  This is issue 3129 in arduino/Arduino and I would like to see it also fixed for the SparkFun SF32u4 boards please.   
https://github.com/arduino/Arduino/pull/3129

This will let us blink the TXLED with pin 24, similar to the way we blink the RXLED with pin 17.

**Comment by dmjlambert** [comment]
This would also apply to sparkfun/Arduino_Boards, is a separate issue needed there to address this or will this issue suffice?

**Comment by rafacouto** [comment]
@dmjlambert Arduino project leaders should merge rafacouto@876669e2921365238b9772443b8cf5a42dfd11fa to avoid desynchronized branches. Thank you for confirming arduino/Arduino#3129

**Comment by BrentWilkins** [comment]
I've added support for D24 in both repos.  Let us know if you discover any more issues.
