### ISSUE TITLE
Please update for Arduino IDE 1.5x

### ISSUE THREAD

**Issue by laapsaap** [sparkfun/SF32u4_boards#5]
Come on, because Arduino IDE 1.5x is still in beta doesnt mean you guys should keep their pace.

We use Yun, an official board that only works with beta version of the IDE. That pretty much sums up what the status is of Arduino 1.5x and what speed they are working.

**Comment by apla** [comment]
Guys from Arduino team already wrote [guide](https://github.com/arduino/Arduino/wiki/Arduino-Hardware-Cores-migration-guide-from-1.0-to-1.6), based on sparkfun boards

**Comment by NicoHood** [comment]
I agree. Its not that big deal guys. In my HID repository (curently the dev tree) is an example on how to us it.

1.6 is coming soon.

**Comment by jimblom** [comment]
1.6 has officially been released! We've updated the contents and structure of this repo to follow along with Arduino's guidelines. The Pro Micro, Fio and MaKey MaKey board definitions should be fully functional with Arduino 1.5.X and higher.

Hardware support for earlier versions of Arduino can still be found [here](https://github.com/sparkfun/SF32u4_boards/releases/tag/pre-1.6).

**Comment by NicoHood** [comment]
Why do you include a full copy of the arduino ide core???
Why not use core=arduino:arduino??

**Comment by cmaglie** [comment]
Hi @jimblom,

NicoHood is right. You probably may want to check this out:

https://github.com/arduino/Arduino/wiki/Arduino-Hardware-Cores-migration-guide-from-1.0-to-1.6

I wrote this guide starting exactly from this core. If you can give me some feedback (working or not) it would be great!

Thanks :-)

**Comment by jimblom** [comment]
That's handy! Thanks for all your help, everyone. I've updated boards.txt and removed the cores folder.

**Comment by NicoHood** [comment]
You should also notice these lines in your variants folder:

https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/leonardo/pins_arduino.h#L93-L94

https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/leonardo/pins_arduino.h#L136

(remove the fixed 30,30,16,12 for the 3 following arrays as well)
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/leonardo/pins_arduino.h#L213

https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/leonardo/pins_arduino.h#L305-L321

https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/leonardo/pins_arduino.h#L341-L359

**Or simply refer to arduino:leonardo as variant. That should do it. The only thing that is different is the BUILTIN_LED definition. But then your files are always up to date.**

If you are interested I could add your pro micro board to my HID project as well. Or you add my definitions to your boards.txt as optional entry. I could upload a PR for this, i just need to know if you are interested in adding it. https://github.com/NicoHood/HID Let my know what you think.

**Comment by NicoHood** [comment]
See https://github.com/sparkfun/SF32u4_boards/pull/13
