### ISSUE TITLE
Fix/Extend the hardware IDs

### ISSUE THREAD

**Issue by ekrempel** [sparkfun/SF32u4_boards#7]
I just got my new pro micro from Thinkersoup (a German re-seller for arduino). The drivers weren't working as the Hardware IDs were not matching. I had to change:

%DESCRIPTION%=DriverInstall, USB\VID_1B4F&PID_9206&MI_00 

to

%DESCRIPTION%=DriverInstall, USB\VID_1B4F&PID_9206

 to get it running. Now the device seems to work fine.

Update: Although the device seemed to run great otherwise, the HID features are not working. I assume this might because of usb 3.0 problems. I reconnected the pro micro to a not usb 3.0 port and the original drivers as well as the HID worked just fine.

**Comment by NicoHood** [comment]
Try to use the teensy drivers. They work for any pid/vid.

[Windows Serial Installer](https://www.pjrc.com/teensy/td_download.html)

**Comment by BrentWilkins** [comment]
First time we have heard about multiple interface setting being an issue.  What OS/version are you running?

**Comment by ToniCorinne** [comment]
Closing this issue out due to lack of response. Please check the new files [here](https://github.com/sparkfun/Arduino_Boards), or open this issue back up if there is still a problem. Thanks!
